# Generated by Django 5.0.6 on 2024-05-15 10:46

import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('generated_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=images.models.upload_to)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(related_name='images', to='images.tag')),
            ],
        ),
    ]
