# Generated by Django 5.0.6 on 2024-05-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_rename_name_image_original_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
    ]
