# Generated by Django 5.0.6 on 2024-05-21 18:54

import storages.backends.azure_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_remove_image_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(to='images.tag'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=storages.backends.azure_storage.AzureStorage(), upload_to='images/'),
        ),
    ]
